import { Words } from './types';

export const WORDS: Words = {
  'Actions (set A)': [
    {
      word: 'cry',
      translation: 'плакать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/cry.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/cry.mp3?raw=true',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/dance.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/dance.mp3?raw=true',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/dive.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/dive.mp3?raw=true',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/draw.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/draw.mp3?raw=true',
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/fish.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/fish.mp3?raw=true',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/fly.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/fly.mp3?raw=true',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/hug.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/hug.mp3?raw=true',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/jump.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/jump.mp3?raw=true',
    },
  ],
  'Actions (set B)' : [
    {
      word: 'open',
      translation: 'открывать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/open.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/open.mp3?raw=true',
    },
    {
      word: 'play',
      translation: 'играть',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/play.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/play.mp3?raw=true',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/point.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/point.mp3?raw=true',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/ride.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/ride.mp3?raw=true',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/run.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/run.mp3?raw=true',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/sing.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/sing.mp3?raw=true',
    },
    {
      word: 'skip',
      translation: 'прыгать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/skip.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/skip.mp3?raw=true',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/swim.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/swim.mp3?raw=true',
    },
  ],
  'Animals (set A)': [
    {
      word: 'cat',
      translation: 'кот',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/cat.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/cat.mp3?raw=true',
    },
    {
      word: 'cow',
      translation: 'корова',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/cow.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/cow.mp3?raw=true',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/chicken.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/chicken.mp3?raw=true',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/dog.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/dog.mp3?raw=true',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/horse.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/horse.mp3?raw=true',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/pig.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/pig.mp3?raw=true',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/rabbit.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/rabbit.mp3?raw=true',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/sheep.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/sheep.mp3?raw=true',
    },
  ],
  'Animals (set B)': [
    {
      word: 'bird',
      translation: 'птица',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/bird.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/bird.mp3?raw=true',
    },
    {
      word: 'elephant',
      translation: 'слон',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/elephant.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/elephant.mp3?raw=true',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/frog.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/frog.mp3?raw=true',
    },
    {
      word: 'giraffe',
      translation: 'жираф',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/giraffe.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/giraffe.mp3?raw=true',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/lion.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/lion.mp3?raw=true',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/mouse.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/mouse.mp3?raw=true',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/turtle.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/turtle.mp3?raw=true',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/dolphin.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/dolphin.mp3?raw=true',
    },
  ],
  'Clothes': [
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/skirt.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/skirt.mp3?raw=true',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/pants.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/pants.mp3?raw=true',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/blouse.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/blouse.mp3?raw=true',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/dress.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/dress.mp3?raw=true',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/boot.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/boot.mp3?raw=true',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/shirt.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/shirt.mp3?raw=true',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/coat.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/coat.mp3?raw=true',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/shoe.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/shoe.mp3?raw=true',
    },
  ],
  'Emotions': [
    {
      word: 'sad',
      translation: 'грустный',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/sad.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/sad.mp3?raw=true',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/angry.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/angry.mp3?raw=true',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/happy.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/happy.mp3?raw=true',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/tired.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/tired.mp3?raw=true',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/surprised.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/surprised.mp3?raw=true',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/scared.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/scared.mp3?raw=true',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/smile.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/smile.mp3?raw=true',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/laugh.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/laugh.mp3?raw=true',
    },
  ], 
  'Body': [
    {
      word: 'hand',
      translation: 'рука',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/hand.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/hand.mp3?raw=true',
    },
    {
      word: 'leg',
      translation: 'нога',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/leg.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/leg.mp3?raw=true',
    },
    {
      word: 'eye',
      translation: 'глаз',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/eye.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/eye.mp3?raw=true',
    },
    {
      word: 'nose',
      translation: 'нос',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/nose.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/nose.mp3?raw=true',
    },
    {
      word: 'ear',
      translation: 'ухо',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/ear.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/ear.mp3?raw=true',
    },
    {
      word: 'mouth',
      translation: 'рот',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/mouth.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/mouth.mp3?raw=true',
    },
    {
      word: 'head',
      translation: 'голова',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/head.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/head.mp3?raw=true',
    },
    {
      word: 'body',
      translation: 'тело',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/body.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/body.mp3?raw=true',
    },
  ],
  'Dishes':  [
    {
      word: 'spoon',
      translation: 'ложка',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/spoon.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/spoon.mp3?raw=true',
    },
    {
      word: 'fork',
      translation: 'вилка',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/fork.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/fork.mp3?raw=true',
    },
    {
      word: 'knife',
      translation: 'нож',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/knife.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/knife.mp3?raw=true',
    },
    {
      word: 'cup',
      translation: 'чашка',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/cup.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/cup.mp3?raw=true',
    },
    {
      word: 'plate',
      translation: 'тарелка',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/plate.jpeg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/plate.mp3?raw=true',
    },
    {
      word: 'pan',
      translation: 'сковорода',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/pan.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/pan.mp3?raw=true',
    },
    {
      word: 'kettle',
      translation: 'чайник',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/kettle.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/kettle.mp3?raw=true',
    },
    {
      word: 'glass',
      translation: 'стакан',
      image: 'https://github.com/EkaterinaMosina/english/blob/main/img/glass.jpg?raw=true',
      audioSrc: 'https://github.com/EkaterinaMosina/english/blob/main/audio/glass.mp3?raw=true',
    },
  ],
}; 