export default {
  FORBID_CLICK: 'forbidden',
  ACTIVE: 'active',
  NOACTIVE: 'noactive',
  MAX_WINNERS_PER_PAGE: 10,
  MAX_CARS_PER_PAGE: 7,
  BASE: 'http://127.0.0.1:3000',
  GARAGE: 'http://127.0.0.1:3000/garage',
  ENGINE: 'http://127.0.0.1:3000/engine',
  WINNERS: 'http://127.0.0.1:3000/winners',
  CAR_FIRST_NAME: [
    'BMW',
    'Aston Martin',
    'Audi',
    'Bugatti',
    'Corvette',
    'McLaren',
    'Dodge',
    'Jaguar',
    'Lamborghini',
    'Lexus',
    'Mazda',
    'Mercedes-Benz',
    'Nissan',
    'Koenigsegg',
    'Pagani',
    'Porsche',
    'Lotus',
    'Shelby',
    'Austin',
    'De Tomaso',
    'Subaru',
    'Volkswagen',
    'Subaru',
    'Chevrolet',
    'Ford',
    'McLaren',
    'Audi',
    'Lotus',
    'Subaru',
    'Porsche',
    'McLaren',
    'Ford',
    'Maserati',
    'Volvo',
    'Mazda',
  ],
  CAR_LAST_NAME: [
    'M3',
    'Vanquish',
    'R8',
    'Veyron',
    'ZR1',
    'MP4/4',
    'Viper',
    'F-Type',
    'Huracan',
    'LFA',
    'MX-5',
    'SLS AMG',
    '300ZX',
    '370Z',
    'Regera',
    'Huayra',
    'Spyder',
    'Exige',
    'Cobra',
    'GT500',
    'Healey',
    'Mangusta',
    'BRZ',
    'GTI',
    'WRX',
    'Camaro',
    'Mustang',
    'MP4/4',
    'Quattro',
    '79',
    'Impreza',
    'W196',
    '956',
    'F1 GTR',
    'RS500',
    'GT',
    '250F',
    'T5 Estate',
    '787B',
  ],
};
