export const SELECT_TOPIC = 'SELECT_TOPIC';
export const CHANGE_MODE = 'CHANGE_MODE';
export const ADD_CARD_ACTION = 'ADD_CARD_ACTION';
export const ADD_STATISTICS = 'ADD_STATISTICS';
export const SELECT_ADMIN_TOPIC = 'SELECT_ADMIN_TOPIC';
export const SELECT_ADMIN_MODE = 'SELECT_ADMIN_MODE';
export const UPDATE_CARDS = 'UPDATE_CARDS';
